添加apache启动脚本

diff --git a/0document/linux-bin b/0document/linux-bin
--- a/0document/linux-bin
+++ b/0document/linux-bin
@@ -176,3 +176,44 @@ sed '1,/^#__THE_END_OF_SHELL__$/d' $0 | tar xzf - -C $WS_PATH/$WS_NAME
      |  -------------------------------------------->sed的行匹配的开始位置
      ----------------------------------------------->sed的匹配从第一行开始
 =============================================================================
+﻿#!/bin/bash(apache启动脚本)
+
+[ -f /etc/rc.d/init.d/functions ] && . /etc/rc.d/init.d/functions
+RETVAL=0
+httpd="/application/apache/bin/httpd"
+start() {
+        $httpd -k start >/dev/null 2>&1
+        # daemon httpd >/dev/null 2>&1
+        RETVAL=$?
+        [ $RETVAL -eq 0 ] && action "启动 httpd:" /bin/true ||\
+        action "启动 httpd:" /bin/false
+        return $RETVAL
+}
+
+stop() {
+        $httpd -k stop >/dev/null 2>&1
+        # killproc httpd >/dev/null 2>&1
+        [ $? -eq 0 ] && action "停止 httpd:" /bin/true ||\
+        action "停止 httpd:" /bin/false
+        return $RETVAL
+}
+case "$1" in
+  start)
+        start
+		;;
+  stop)
+        stop
+        ;;
+  restart)
+       
+       sh $0 stop
+       sh $0 start
+        ;;
+   *)
+        echo "Format error!"
+        echo $"Usage: $0 {start|stop|restart}"
+        exit 1
+        ;;
+esac
+exit $RETVAL
+=============================================================================
